export const SELECT_MOVIE: string = 'SELECT_MOVIE'
export const CLEAR_SELECTED_MOVIE: string = 'CLEAR_SELECTED_MOVIE'
export const SET_MOVIES_LIST: string = 'SET_MOVIES_LIST'
export const SET_GENRE_FILTER: string = 'SET_GENRE_FILTER'
export const CLEAR_GENRE_FILTER: string = 'CLEAR_GENRE_FILTER'
