export const MOVIES_LIST: string = 'MOVIES_LIST'
export const GENRES_LIST: string = 'GENRES_LIST'
export const SELECTED_MOVIE: string = 'SELECTED_MOVIE'
export const MOVIE_GENRE_FILTER: string = 'MOVIE_GENRE_FILTER'
export const MOVIE_NAME_FILTER: string = 'MOVIE_NAME_FILTER'
